# This file is automatically generated by Django and shouldn't be modified manually.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='apks/')),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
